export interface Credentials {
  schoolID: string;
  childID: string;
  gender: 'M' | 'F';
  childgender:string;
  parents: string;
  parentage: string;
  childage: string;
  childageInMonths: string;
  monthchild: string;
  classs: string;
  living: string;
  education1: string;
  profession1: string;
  levelofreligiousty: string;
  education2: string;
  profession2: string;
  languages : string;
  extralanguage: string;
  economic_level: string;
  lab : string;
  applanguages1:string;
  applanguages2:string;
  attention1:string;
  attention2:string;
  attention3:string;
  prizeDonated:string;
  appearedpyramid:string;
  snakeScore:string;
}
